---
- name: get the Azure env ready for satellite deployments
  hosts: localhost
  gather_facts: false
  vars:
    RG_name: cloud-shell-storage-eastus
  tasks:
  - name: Create storage account
#    azure.azcollection.azure_rm_storageaccount:
    azure_rm_storageaccount:
      resource_group: "{{ RG_name }}"
# name of the storage container needs to be globally unique
      name: gsowell002
      account_type: Standard_LRS

  - name: Create virtual network
    azure_rm_virtualnetwork:
      resource_group: "{{ RG_name }}"
      name: testvn001
      address_prefixes: "172.29.0.0/16"

  - name: Add subnet
    azure_rm_subnet:
      resource_group: "{{ RG_name }}"
      name: subnet001
      address_prefix: "172.29.0.0/24"
      virtual_network: testvn001

  - name: Create security group that allows SSH
    azure_rm_securitygroup:
      resource_group: "{{ RG_name }}"
      name: secgroup001
      rules:
        - name: SSH
          protocol: Tcp
          destination_port_range: 22
          access: Allow
          priority: 101
          direction: Inbound

  - name: Create NIC for testing purposes
    azure_rm_networkinterface:
      resource_group: "{{ RG_name }}"
      name: testnic001
      virtual_network: testvn001
      subnet: subnet001
      security_group: secgroup001

  - name: Create public ip
    azure_rm_publicipaddress:
      resource_group: "{{ RG_name }}"
      allocation_method: Dynamic
      name: vgwipaddr

# only complete this portion for VPN tunnel building

  - name: Add gateway subnet for VPN tunnel
    azure_rm_subnet:
      resource_group: "{{ RG_name }}"
      name: GatewaySubnet
      address_prefix: "172.29.1.0/27"
      virtual_network: testvn001

  - name: Create virtual network gateway for VPN tunnel
    azure_rm_virtualnetworkgateway:
      resource_group: "{{ RG_name }}"
      name: GregVirtualNetworkGateway
      ip_configurations:
        - name: testipconfig
          private_ip_allocation_method: Dynamic
          public_ip_address_name: vgwipaddr
      virtual_network: testvn001

###no module for creating local network gateway *putting in info for remote VPN endpoint*
###https://docs.microsoft.com/en-us/azure/vpn-gateway/tutorial-site-to-site-portal
